# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc.vpc-cicd:
resource "aws_vpc" "vpc-cicd" {
  assign_generated_ipv6_cidr_block = false
  cidr_block                       = "172.30.0.0/24"
  enable_classiclink               = false
  enable_classiclink_dns_support   = false
  enable_dns_hostnames             = false
  enable_dns_support               = true
  instance_tenancy                 = "default"
  tags = {
    "Name"     = "eks-cicd"
    "workshop" = "eks-cicd"
  }
}
