# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-i1:
resource "aws_subnet" "subnet-i1" {
  depends_on=[aws_vpc_ipv4_cidr_block_association.vpc-cidr-assoc]
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1a"
  cidr_block                      = "100.64.0.0/18"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "i1-mycluster1"
 #   "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
  #  "kubernetes.io/role/internal-elb"             = "1"
     "workshop" = "subnet-i1"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-i2:
resource "aws_subnet" "subnet-i2" {
  depends_on=[aws_vpc_ipv4_cidr_block_association.vpc-cidr-assoc]
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1b"
  cidr_block                      = "100.64.64.0/18"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "i2-mycluster1"
 #   "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
  #  "kubernetes.io/role/internal-elb"             = "1"
    "workshop" = "subnet-i2"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-i3:
resource "aws_subnet" "subnet-i3" {
  depends_on=[aws_vpc_ipv4_cidr_block_association.vpc-cidr-assoc]
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1c"
  cidr_block                      = "100.64.128.0/18"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "i3-mycluster1"
 #   "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
   # "kubernetes.io/role/internal-elb"             = "1"
    "workshop" = "subnet-i3"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-p1:
resource "aws_subnet" "subnet-p1" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1a"
  cidr_block                      = "10.0.1.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "Private1"
 #   "alpha.eksctl.io/cluster-name"                = "mycluster1"
 #   "alpha.eksctl.io/eksctl-version"              = "0.29.2"
 #   "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
    "workshop" = "subnet-p1"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}


output "sub-priv1" {
  value = aws_subnet.subnet-p1.id
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-p2:
resource "aws_subnet" "subnet-p2" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1b"
  cidr_block                      = "10.0.2.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "Private2"
#    "alpha.eksctl.io/cluster-name"                = "mycluster1"
#    "alpha.eksctl.io/eksctl-version"              = "0.29.2"
#    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
    "workshop" = "subnet-p2"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}

output "sub-priv2" {
  value = aws_subnet.subnet-p2.id
}# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-p3:
resource "aws_subnet" "subnet-p3" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1c"
  cidr_block                      = "10.0.3.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "Private3"
 #   "alpha.eksctl.io/cluster-name"                = "mycluster1"
 #   "alpha.eksctl.io/eksctl-version"              = "0.29.2"
 #   "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
    "workshop" = "subnet-p3"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}

output "sub-priv3" {
  value = aws_subnet.subnet-p3.id
}