# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.eksctl-ateksf1-cluster-FargatePodExecutionRole-86R6T0RQZPHM__AmazonEKSFargatePodExecutionRolePolicy:
resource "aws_iam_role_policy_attachment" "AmazonEKSFargatePodExecutionRolePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy"
  role       = aws_iam_role.FargatePodExecutionRole.id
}

## attach logging policy
resource "aws_iam_role_policy_attachment" "eks-fargate-logging-policy" {
  policy_arn = aws_iam_policy.eks-fargate-logging-policy.arn
  role       = aws_iam_role.FargatePodExecutionRole.id
}


