# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app:
resource "aws_iam_role" "AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "codepipeline.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  max_session_duration  = 3600
  name                  = "AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app"
  path                  = "/service-role/"
  tags                  = {}
}
