# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_codepipeline.pipe-eksworkshop-app:
resource "aws_codepipeline" "pipe-eksworkshop-app" {
  name       = "pipe-eksworkshop-app"
  depends_on = [aws_iam_role.AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app]
  role_arn   = aws_iam_role.AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app.arn
  tags       = {}

  artifact_store {
    location = "aws_s3_bucket.codepipeline-bucket.bucket"
    type     = "S3"
  }

  stage {
    name = "Source"

    action {
      category = "Source"
      configuration = {
        "BranchName"           = "master"
        "OutputArtifactFormat" = "CODE_ZIP"
        "PollForSourceChanges" = "false"
        "RepositoryName"       = "eksworkshop-app"
      }
      input_artifacts = []
      name            = "Source"
      namespace       = "SourceVariables"
      output_artifacts = [
        "SourceArtifact",
      ]
      owner     = "AWS"
      provider  = "CodeCommit"
      region    = "eu-west-1"
      run_order = 1
      version   = "1"
    }
  }
  stage {
    name = "Build"

    action {
      category = "Build"
      configuration = {
        "ProjectName" = "eks-cicd-build-app"
      }
      input_artifacts = [
        "SourceArtifact",
      ]
      name      = "Build"
      namespace = "BuildVariables"
      output_artifacts = [
        "BuildArtifact",
      ]
      owner     = "AWS"
      provider  = "CodeBuild"
      region    = "eu-west-1"
      run_order = 1
      version   = "1"
    }
  }
}
