# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app__AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app:
resource "aws_iam_role_policy_attachment" "AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app__AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app" {
  policy_arn = "arn:aws:iam::566972129213:policy/service-role/AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app"
  role       = aws_iam_role.AWSCodePipelineServiceRole-eu-west-1-pipe-eksworkshop-app.id
}
