# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc.vpc-0528d1e3f0b31cefe:
resource "aws_vpc" "vpc-0528d1e3f0b31cefe" {
  assign_generated_ipv6_cidr_block = false
  cidr_block                       = "192.168.0.0/16"
  enable_dns_hostnames             = true
  enable_dns_support               = true
  instance_tenancy                 = "default"
  tags = {
    "Name"                                        = "eksctl-manamieks-cluster/VPC"
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
  }
}
