# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-029eb518ff8c1739a:
resource "aws_route_table_association" "rtbassoc-p1" {
  route_table_id = aws_route_table.rtb-p1.id
  subnet_id      = aws_subnet.subnet-p1.id
}

