# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-0c3e14aeb276186c2:
resource "aws_route_table_association" "rtbassoc-p2" {
  route_table_id = aws_route_table.rtb-p2.id
  subnet_id      = aws_subnet.subnet-p2.id
}
