# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eks_cluster.cluster:
resource "aws_eks_cluster" "cluster" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
  name = var.cluster-name

  role_arn = data.aws_ssm_parameter.cluster_service_role_arn
  tags     = {}
  version  = var.eks_version

  timeouts {}

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = false
    public_access_cidrs = [
      "0.0.0.0/0",
    ]
    security_group_ids = [
      data.aws_ssm_parameter.net-cluster-sg,
    ]
    subnet_ids = [
      data.aws_ssm_parameter.sub-priv1,
      data.aws_ssm_parameter.sub-priv2,
      data.aws_ssm_parameter.sub-priv3,
    ]
  }
  encryption_config {
    provider {
      key_arn = data.aws_kms_key.ekskey.arn
    }
    resources = ["secrets"]
  }
  provisioner "local-exec" {
    command     = "until curl --output /dev/null --insecure --silent ${self.endpoint}/healthz; do sleep 1; done"
    working_dir = path.module
  }

}

