# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_eks_cluster.manamieksp:
resource "aws_eks_cluster" "manamieksp" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
  name       = "manamieksp"
  depends_on = [aws_iam_role.eksctl-manamieksp-cluster-ServiceRole-HUIGIC7K7HNJ]
  role_arn   = aws_iam_role.eksctl-manamieksp-cluster-ServiceRole-HUIGIC7K7HNJ.arn
  tags       = {}
  version    = "1.17"

  timeouts {}

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = false
    public_access_cidrs = [
      "0.0.0.0/0",
    ]
    security_group_ids = [
      aws_security_group.sg-0a1578a53b37b12c6.id,
    ]
    subnet_ids = [
      aws_subnet.subnet-00d48938ae75575f6.id,
      aws_subnet.subnet-0c29b7ba0fae1c061.id,
      aws_subnet.subnet-0eed8d110fe361191.id,
    ]
  }
}
