# Terraform and Provider Configuration
# This is the bootstrap stage - uses local state initially
# Subsequent stages will use the S3 backend generated by this stage

terraform {
  # Minimum version required for features used in this project
  required_version = "> 1.12.0"
  
  required_providers {
    # AWS provider locked to specific version to prevent breaking changes
    aws = {
      source = "hashicorp/aws"
      version = "5.100.0"  # Locked version for stability
    }
    # Used for triggering gen-backend.sh script
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2.0"
    }
    # Used for external data sources if needed
    external = {
      source  = "hashicorp/external"
      version = "~> 2.3.1"
    }
    # Required for subsequent stages that manage K8s resources
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.24.0"
    }
    # Required for subsequent stages that deploy Helm charts
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17.0"
    }
    # Required for advanced K8s manifest management
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14"
    }
    # Used for local file operations
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4.0"
    }

  }
}

# AWS Provider configuration
# Uses local credentials file for authentication
provider "aws" {
  region                   = var.region
  shared_credentials_files = ["~/.aws/credentials"]
  # profile parameter available but commented out - using default profile
  #profile                  = var.profile
}

# Additional providers required by this configuration
provider "null" {}
provider "external" {}



