# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role.eksctl-manamieksp-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO:
resource "aws_iam_role" "eksctl-manamieksp-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ec2.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  max_session_duration  = 3600
  name                  = "eksctl-manamieksp-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO"
  path                  = "/"
  tags = {
    "Name"                                        = "eksctl-manamieksp-nodegroup-ng-maneksami2/NodeInstanceRole"
    "alpha.eksctl.io/cluster-name"                = "manamieksp"
    "alpha.eksctl.io/eksctl-version"              = "0.29.2"
    "alpha.eksctl.io/nodegroup-name"              = "ng-maneksami2"
    "alpha.eksctl.io/nodegroup-type"              = "managed"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieksp"
  }
}
