# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.codebuild-eks-cicd-build-app-service-role__CodeBuildVpcPolicy-eks-cicd-build-app-eu-west-1:
resource "aws_iam_role_policy_attachment" "codebuild-eks-cicd-build-app-service-role__CodeBuildVpcPolicy-eks-cicd-build-app-eu-west-1" {
  policy_arn = "arn:aws:iam::566972129213:policy/service-role/CodeBuildVpcPolicy-eks-cicd-build-app-eu-west-1"
  role       = aws_iam_role.codebuild-eks-cicd-build-app-service-role.id
}
