# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy_attachment.eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ__AmazonEKSClusterPolicy:
resource "aws_iam_role_policy_attachment" "eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ__AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ.id
}
