# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role.eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ:
resource "aws_iam_role" "eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = [
              "eks-fargate-pods.amazonaws.com",
              "eks.amazonaws.com",
            ]
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  max_session_duration  = 3600
  name                  = "eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ"
  path                  = "/"
  tags = {
    "Name"                                        = "eksctl-mycluster1-cluster/ServiceRole"
    "alpha.eksctl.io/cluster-name"                = "mycluster1"
    "alpha.eksctl.io/eksctl-version"              = "0.29.2"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
  }
}

output "cluster_service_role_arn" {
  value = aws_iam_role.eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ.arn
}
