# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-mycluster1-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO__eksctl-mycluster1-nodegroup-ng-maneksami2-PolicyCertManagerHostedZones:
resource "aws_iam_role_policy" "eksctl-mycluster1-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO__eksctl-mycluster1-nodegroup-ng-maneksami2-PolicyCertManagerHostedZones" {
  name = "eksctl-mycluster1-nodegroup-ng-maneksami2-PolicyCertManagerHostedZones"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "route53:ListResourceRecordSets",
            "route53:ListHostedZonesByName",
            "route53:ListHostedZones",
            "route53:ListTagsForResource",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-mycluster1-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO.id
}
