# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-0eca7ac73091a9f16:
resource "aws_route_table_association" "rtbassoc-0eca7ac73091a9f16" {
  route_table_id = aws_route_table.rtb-098ac5c276ee3a48e.id
  subnet_id      = aws_subnet.subnet-08dad7366e061da93.id
}
