# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_eip.eipalloc-00bf2757761c8ed12:
resource "aws_eip" "eipalloc-00bf2757761c8ed12" {
  public_ipv4_pool = "amazon"
  tags = {
    "Name"                                        = "eksctl-manamieks-cluster/NATIP"
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
  }
  vpc = true

  timeouts {}
}
