# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieks-cluster-ServiceRole-HX498SOE260J__eksctl-manamieks-cluster-PolicyELBPermissions:
resource "aws_iam_role_policy" "eksctl-manamieks-cluster-ServiceRole-HX498SOE260J__eksctl-manamieks-cluster-PolicyELBPermissions" {
  name = "eksctl-manamieks-cluster-PolicyELBPermissions"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ec2:DescribeAccountAttributes",
            "ec2:DescribeAddresses",
            "ec2:DescribeInternetGateways",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieks-cluster-ServiceRole-HX498SOE260J.id
}
