# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy_attachment.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__CloudWatchAgentServerPolicy:
resource "aws_iam_role_policy_attachment" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__CloudWatchAgentServerPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
  role       = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
