# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-0eb5ebf6fd5e14e09:
resource "aws_route_table_association" "rtbassoc-0eb5ebf6fd5e14e09" {
  route_table_id = aws_route_table.rtb-0329e787bbafcb2c4.id
  subnet_id      = aws_subnet.subnet-00d48938ae75575f6.id
}
