# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-065fa5ab0194a82cd:
resource "aws_route_table_association" "rtbassoc-065fa5ab0194a82cd" {
  route_table_id = aws_route_table.rtb-01c9dbedbe4f69691.id
  subnet_id      = aws_subnet.subnet-0ca14ea12ad0de3c4.id
}
