# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_launch_template.lt-037df4653a1121595:
resource "aws_launch_template" "lt-037df4653a1121595" {
  disable_api_termination = false
  image_id                = "ami-0ba76231e2506911c"
  instance_type           = "t3.small"
  key_name                = "terraform-andyt"
  name                    = "at-ltami-eks"
  tags                    = {}
  user_data               = "TUlNRS1WZXJzaW9uOiAxLjAKQ29udGVudC1UeXBlOiBtdWx0aXBhcnQvbWl4ZWQ7IGJvdW5kYXJ5PSI9PU1ZQk9VTkRBUlk9PSIKCi0tPT1NWUJPVU5EQVJZPT0KQ29udGVudC1UeXBlOiB0ZXh0L3gtc2hlbGxzY3JpcHQ7IGNoYXJzZXQ9InVzLWFzY2lpIgoKIyEvYmluL2Jhc2gKZWNobyAiUnVubmluZyBjdXN0b20gdXNlciBkYXRhIHNjcmlwdCIKL2V0Yy9la3MvYm9vdHN0cmFwLnNoIG1hbmFtaWVrcyAtLWt1YmVsZXQtZXh0cmEtYXJncyAnLS1ub2RlLWxhYmVscz1la3MuYW1hem9uYXdzLmNvbS9ub2RlZ3JvdXA9Y3VzdG9tLW5nYW1pLGVrcy5hbWF6b25hd3MuY29tL25vZGVncm91cC1pbWFnZT1hbWktMGJhNzYyMzFlMjUwNjkxMWMnCmVjaG8gIlJ1bm5pbmcgY3VzdG9tIHVzZXIgZGF0YSBzY3JpcHQiID4gL3RtcC9tZS50eHQKeXVtIGluc3RhbGwgLXkgYW1hem9uLXNzbS1hZ2VudAplY2hvICJ5dW0nZCBhZ2VudCIgPj4gL3RtcC9tZS50eHQKc3lzdGVtY3RsIGVuYWJsZSBhbWF6b24tc3NtLWFnZW50ICYmIHN5c3RlbWN0bCBzdGFydCBhbWF6b24tc3NtLWFnZW50CmRhdGUgPj4gL3RtcC9tZS50eHQKCi0tPT1NWUJPVU5EQVJZPT0tLQ=="
  vpc_security_group_ids  = []
}
