# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy_attachment.eksctl-manamieks-cluster-ServiceRole-HX498SOE260J__AmazonEKSClusterPolicy:
resource "aws_iam_role_policy_attachment" "eksctl-manamieks-cluster-ServiceRole-HX498SOE260J__AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.eksctl-manamieks-cluster-ServiceRole-HX498SOE260J.id
}
