# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_eks_node_group.manamieks_custom-ngami:
resource "aws_eks_node_group" "manamieks_custom-ngami" {
  depends_on     = [aws_eks_cluster.manamieks]
  cluster_name   = "manamieks"
  disk_size      = 0
  instance_types = []
  labels = {
    "alpha.eksctl.io/cluster-name"   = "manamieks"
    "alpha.eksctl.io/nodegroup-name" = "custom-ngami"
  }
  node_group_name = "custom-ngami"
  node_role_arn   = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.arn
  subnet_ids = [
    aws_subnet.subnet-08dad7366e061da93.id,
    aws_subnet.subnet-0ca14ea12ad0de3c4.id,
    aws_subnet.subnet-0cc9b935aa4a049e1.id,
  ]
  tags = {
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "alpha.eksctl.io/nodegroup-name"              = "custom-ngami"
    "alpha.eksctl.io/nodegroup-type"              = "managed"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
  }

  launch_template {
    name    = aws_launch_template.lt-037df4653a1121595.name
    version = "1"
  }

  scaling_config {
    desired_size = 2
    max_size     = 3
    min_size     = 1
  }

  timeouts {}
}
