# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyEFS:
resource "aws_iam_role_policy" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyEFS" {
  name = "eksctl-manamieks-nodegroup-custom-ngami-PolicyEFS"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "elasticfilesystem:*",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
