# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_eks_cluster.manamieks:
resource "aws_eks_cluster" "manamieks" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
  name       = "manamieks"
  depends_on = [aws_iam_role.eksctl-manamieks-cluster-ServiceRole-HX498SOE260J]
  role_arn   = aws_iam_role.eksctl-manamieks-cluster-ServiceRole-HX498SOE260J.arn
  tags       = {}
  version    = "1.17"

  timeouts {}

  vpc_config {
    endpoint_private_access = false
    endpoint_public_access  = true
    public_access_cidrs = [
      "0.0.0.0/0",
    ]

    subnet_ids = [
      aws_subnet.subnet-08dad7366e061da93.id,
      aws_subnet.subnet-0c9bda2cedc5060a5.id,
      aws_subnet.subnet-0ca14ea12ad0de3c4.id,
      aws_subnet.subnet-0cc9b935aa4a049e1.id,
      aws_subnet.subnet-0dbd0e98cc1c333a4.id,
      aws_subnet.subnet-0fb6aa031219d3720.id,
    ]
  }
}
