# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieksp-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO__eksctl-manamieksp-nodegroup-ng-maneksami2-PolicyEFSEC2:
resource "aws_iam_role_policy" "eksctl-manamieksp-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO__eksctl-manamieksp-nodegroup-ng-maneksami2-PolicyEFSEC2" {
  name = "eksctl-manamieksp-nodegroup-ng-maneksami2-PolicyEFSEC2"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ec2:DescribeSubnets",
            "ec2:CreateNetworkInterface",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DeleteNetworkInterface",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:DescribeNetworkInterfaceAttribute",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieksp-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO.id
}
