# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_subnet.subnet-0e2bfefc0f0f83e59:
resource "aws_subnet" "subnet-0e2bfefc0f0f83e59" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1a"
  cidr_block                      = "100.64.0.0/19"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "i1-manamieksp"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieksp"
    "kubernetes.io/cluster/manamieksp"            = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
  }
  vpc_id = aws_vpc.vpc-0c5887ebf50affcd7.id

  timeouts {}
}
