# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-015e1f8a1237ecb62:
resource "aws_route_table_association" "rtbassoc-015e1f8a1237ecb62" {
  route_table_id = aws_route_table.rtb-0bb09ea15fdbbad39.id
  subnet_id      = aws_subnet.subnet-0c9bda2cedc5060a5.id
}
