# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyEFSEC2:
resource "aws_iam_role_policy" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyEFSEC2" {
  name = "eksctl-manamieks-nodegroup-custom-ngami-PolicyEFSEC2"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ec2:DescribeSubnets",
            "ec2:CreateNetworkInterface",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DeleteNetworkInterface",
            "ec2:ModifyNetworkInterfaceAttribute",
            "ec2:DescribeNetworkInterfaceAttribute",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
