# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_internet_gateway.igw-078678d961a407d7f:
resource "aws_internet_gateway" "igw-078678d961a407d7f" {
  tags = {
    "Name"                                        = "eksctl-manamieks-cluster/InternetGateway"
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
  }
  vpc_id = aws_vpc.vpc-0528d1e3f0b31cefe.id
}
