# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-0d69817e6033e883d:
resource "aws_route_table_association" "rtbassoc-0d69817e6033e883d" {
  route_table_id = aws_route_table.rtb-0bb09ea15fdbbad39.id
  subnet_id      = aws_subnet.subnet-0fb6aa031219d3720.id
}
