# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc_ipv4_cidr_block_association.vpc-cidr-assoc-045e8d103817adaea:
resource "aws_vpc_ipv4_cidr_block_association" "vpc-cidr-assoc-045e8d103817adaea" {
  cidr_block = "100.64.0.0/16"
  vpc_id     = aws_vpc.vpc-0c5887ebf50affcd7.id

  timeouts {}
}
