# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyCertManagerHostedZones:
resource "aws_iam_role_policy" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyCertManagerHostedZones" {
  name = "eksctl-manamieks-nodegroup-custom-ngami-PolicyCertManagerHostedZones"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "route53:ListResourceRecordSets",
            "route53:ListHostedZonesByName",
            "route53:ListHostedZones",
            "route53:ListTagsForResource",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
