# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table.rtb-019ad6d895fc977fc:
resource "aws_route_table" "rtb-019ad6d895fc977fc" {
  propagating_vgws = []
  route            = []
  tags             = {}
  vpc_id           = aws_vpc.vpc-0528d1e3f0b31cefe.id
}
