# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyAutoScaling:
resource "aws_iam_role_policy" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyAutoScaling" {
  name = "eksctl-manamieks-nodegroup-custom-ngami-PolicyAutoScaling"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup",
            "ec2:DescribeLaunchTemplateVersions",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
