# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy_attachment.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__AmazonEKS_CNI_Policy:
resource "aws_iam_role_policy_attachment" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
