# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC:
resource "aws_iam_role" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ec2.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  max_session_duration  = 3600
  name                  = "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC"
  path                  = "/"
  tags = {
    "Name"                                        = "eksctl-manamieks-nodegroup-custom-ngami/NodeInstanceRole"
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "alpha.eksctl.io/nodegroup-name"              = "custom-ngami"
    "alpha.eksctl.io/nodegroup-type"              = "managed"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
  }
}
