# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table.rtb-0939e7f3ae6e7b829:
resource "aws_route_table" "rtb-0939e7f3ae6e7b829" {
  propagating_vgws = []
  route            = []
  tags             = {}
  vpc_id           = aws_vpc.vpc-0c5887ebf50affcd7.id
}
