# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-081730072ed2df960:
resource "aws_route_table_association" "rtbassoc-081730072ed2df960" {
  route_table_id = aws_route_table.rtb-0bb09ea15fdbbad39.id
  subnet_id      = aws_subnet.subnet-0dbd0e98cc1c333a4.id
}
