# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_nat_gateway.nat-05b5eb1db80236f5f:
resource "aws_nat_gateway" "nat-05b5eb1db80236f5f" {
  allocation_id = aws_eip.eipalloc-00bf2757761c8ed12.id
  subnet_id     = aws_subnet.subnet-0c9bda2cedc5060a5.id
  tags = {
    "Name"                                        = "eksctl-manamieks-cluster/NATGateway"
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
  }
}
