# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc_peering_connection.pcx-0e111fb23e4eee730:
resource "aws_vpc_peering_connection" "pcx-0e111fb23e4eee730" {
  peer_owner_id = "566972129213"
  peer_region   = "eu-west-1"
  peer_vpc_id   = "vpc-d16a7cb7"
  tags          = {}
  vpc_id        = aws_vpc.vpc-0c5887ebf50affcd7.id

  accepter {
    allow_classic_link_to_remote_vpc = false
    allow_remote_vpc_dns_resolution  = false
    allow_vpc_to_remote_classic_link = false
  }

  requester {
    allow_classic_link_to_remote_vpc = false
    allow_remote_vpc_dns_resolution  = false
    allow_vpc_to_remote_classic_link = false
  }

  timeouts {}
}
