# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_subnet.subnet-0fb6aa031219d3720:
resource "aws_subnet" "subnet-0fb6aa031219d3720" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-2c"
  cidr_block                      = "192.168.64.0/19"
  map_public_ip_on_launch         = true
  tags = {
    "Name"                                        = "eksctl-manamieks-cluster/SubnetPublicEUWEST2C"
    "alpha.eksctl.io/cluster-name"                = "manamieks"
    "alpha.eksctl.io/eksctl-version"              = "0.28.1"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "manamieks"
    "kubernetes.io/cluster/manamieks"             = "shared"
    "kubernetes.io/role/elb"                      = "1"
  }
  vpc_id = aws_vpc.vpc-0528d1e3f0b31cefe.id

  timeouts {}
}
