# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_iam_role_policy.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyCertManagerChangeSet:
resource "aws_iam_role_policy" "eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC__eksctl-manamieks-nodegroup-custom-ngami-PolicyCertManagerChangeSet" {
  name = "eksctl-manamieks-nodegroup-custom-ngami-PolicyCertManagerChangeSet"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "route53:ChangeResourceRecordSets",
          ]
          Effect   = "Allow"
          Resource = "arn:aws:route53:::hostedzone/*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  role = aws_iam_role.eksctl-manamieks-nodegroup-custom-NodeInstanceRole-5ZHV97469VKC.id
}
