# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_eks_cluster.mycluster1:
resource "aws_eks_cluster" "mycluster1" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
  name       = "mycluster1"
  #depends_on = [data.terraform_remote_state.iam.aws_iam_role.eksctl-mycluster1-cluster-ServiceRole-HUIGIC7K7HNJ]
  role_arn   = data.terraform_remote_state.iam.outputs.cluster_service_role_arn
  tags       = {}
  version    = "1.17"

  timeouts {}

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = false
    public_access_cidrs = [
      "0.0.0.0/0",
    ]
    security_group_ids = [
      data.terraform_remote_state.net.outputs.cluster-sg,
    ]
    subnet_ids = [
      data.terraform_remote_state.net.outputs.sub-priv1,
      data.terraform_remote_state.net.outputs.sub-priv2,
      data.terraform_remote_state.net.outputs.sub-priv3,
    ]
  }
}

output cluster-name {
  value=aws_eks_cluster.mycluster1.name
}

output cluster-sg {
  value=aws_eks_cluster.mycluster1.vpc_config[0].cluster_security_group_id
}
