# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-07b271e3a84d0d94a:
resource "aws_nat_gateway" "nat-07b271e3a84d0d94a" {
  allocation_id = aws_eip.eipalloc-052dd24eaa93ed064.id
  subnet_id     = aws_subnet.subnet-05937b8ca518f111e.id
  tags = {
    "Name" = "ngw-eks-cicd"
  }
}
