# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_subnet.subnet-i2:
resource "aws_subnet" "subnet-i2" {
  depends_on=[aws_vpc_ipv4_cidr_block_association.vpc-cidr-assoc]
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1b"
  cidr_block                      = "100.64.64.0/18"
  map_public_ip_on_launch         = false
  tags = {
    "Name"                                        = "i2-mycluster1"
    "eksctl.cluster.k8s.io/v1alpha1/cluster-name" = "mycluster1"
    "kubernetes.io/cluster/mycluster1"            = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
  }
  vpc_id = aws_vpc.vpc-mycluster1.id

  timeouts {}
}
