# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-049d94408cba62cca:
resource "aws_route_table_association" "rtbassoc-i2" {
  route_table_id = aws_route_table.rtb-i.id
  subnet_id      = aws_subnet.subnet-i2.id
}
