# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc_ipv4_cidr_block_association.vpc-cidr-assoc:
resource "aws_vpc_ipv4_cidr_block_association" "vpc-cidr-assoc" {
  cidr_block = "100.64.0.0/16"
  vpc_id     = aws_vpc.vpc-mycluster1.id

  timeouts {}
}
