# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc.vpc-vpc-:
resource "aws_vpc" "cluster" {
  assign_generated_ipv6_cidr_block = false
  cidr_block                       = "10.0.0.0/22"
  enable_dns_hostnames             = true
  enable_dns_support               = true
  instance_tenancy                 = "default"
  tags = {
    "Name"                                        = format("eks-%s-cluster",data.aws_ssm_parameter.tf-eks-cluster-name.value)
  }
}

output "eks-vpc" {
  value = aws_vpc.cluster.id
}

output "eks-cidr" {
  value = aws_vpc.cluster.cidr_block
}
