# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc_endpoint.vpce-06c6009f81277acd2:
resource "aws_vpc_endpoint" "vpce-s3" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2008-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids =  data.aws_route_tables.rts.ids 
    
  security_group_ids = []
  service_name       = "com.amazonaws.eu-west-2.s3"
  subnet_ids         = []
  tags               = {}
  vpc_endpoint_type  = "Gateway"
  vpc_id             = data.aws_eks_cluster.cluster.vpc_config[0].vpc_id

  timeouts {}
}
