# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc_endpoint.vpce-0e16c6e13268cd282:
resource "aws_vpc_endpoint" "vpce-0e16c6e13268cd282" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0ace39edbaa9f6b27.id,
  ]
  service_name = "com.amazonaws.eu-west-2.ec2"
  subnet_ids = [
    aws_subnet.subnet-008b558038fd66824.id,
    aws_subnet.subnet-06160beb7556bec90.id,
    aws_subnet.subnet-0761b06769899a866.id,
  ]
  tags              = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0cbe7611fb4cfebea.id

  timeouts {}
}
