# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_vpc_endpoint.vpce-057599374c5db5168:
resource "aws_vpc_endpoint" "vpce-ec2messages" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    data.aws_eks_cluster.cluster.vpc_config[0].cluster_security_group_id,
  ]
  service_name = "com.amazonaws.eu-west-2.ec2messages"

  tags              = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = data.aws_eks_cluster.cluster.vpc_config[0].vpc_id

  timeouts {}
}
